import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/Header'
import Nav from '../src/components/Nav'
import Results from '../src/components/Results'
import requests, { Response } from '@utils/requests'
import { getFromTMDB } from '../src/utils/tmdb'

const Home: NextPage<Props> = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  )
}

type Props = {
  results: Response | null
}

export const getServerSideProps: GetServerSideProps<Props> = async (ctx) => {
  const { genre } = ctx.query
  const url = requests[genre as string]?.url || requests['trending'].url

  let results: Response | null
  try {
    const { data } = await getFromTMDB(url)
    results = data
  } catch (error) {
    results = null
  }

  return { props: { results } }
}

export default Home
