import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/Header'
import Nav from '../src/components/Nav'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
    </div>
  )
}

export default Home
